#!/usr/bin/env bash
# This script reconfigures host ip addresses

echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8   facebook.com" >> /etc/hosts

# This doesnt seem like an efficient way to modify this file
